# Generated by Django 3.1.5 on 2022-01-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flows_1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flowid', models.IntegerField()),
                ('nodename', models.CharField(blank=True, max_length=100, null=True)),
                ('relationship', models.CharField(default='NA', max_length=100)),
            ],
        ),
    ]
