# Generated by Django 3.2.7 on 2022-01-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainUsersHashTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(max_length=100)),
                ('hash', models.CharField(blank=True, max_length=100, null=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('used', models.CharField(blank=True, max_length=100, null=True)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'domain_users_hash_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DomainUsersPasswordTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('used', models.CharField(blank=True, max_length=100, null=True)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'domain_users_password_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FinalHostsTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, db_column='OS', max_length=100, null=True)),
                ('subnet', models.CharField(blank=True, max_length=100, null=True)),
                ('compromised', models.CharField(blank=True, max_length=100, null=True)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'final_hosts_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FindingsTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('risk', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.CharField(blank=True, max_length=100, null=True)),
                ('attackmitre', models.CharField(blank=True, max_length=100, null=True)),
                ('sia', models.CharField(blank=True, max_length=100, null=True)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'findings_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='flows_1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flowid', models.IntegerField()),
                ('nodename', models.CharField(blank=True, max_length=100, null=True)),
                ('relationship', models.CharField(default='NA', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='issue1Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'issue1_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='issue2Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'issue2_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='issue3Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'issue3_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='issue4Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'issue4_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='issue5Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'issue5_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='issue6Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'issue6_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='issue7Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'issue7_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MssqlTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mssql_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PathsTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('pathid', models.IntegerField()),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('compromiseduser', models.CharField(db_column='compromisedUser', max_length=100)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'paths_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProgressTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'progress_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RevalidationTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability', models.CharField(blank=True, max_length=100, null=True)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'revalidation_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScanIdTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
            ],
            options={
                'db_table': 'scan_id_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service135Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_135_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service137Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_137_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service1433Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_1433_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service1521Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_1521_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service17988Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_17988_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service2049Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_2049_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service21Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_21_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service22Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_22_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service23Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_23_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service25Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_25_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service27017Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_27017_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service3250Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_3250_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service3260Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_3260_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service3306Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_3306_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service3389Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_3389_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service389Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_389_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service443Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_443_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service445Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_445_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service5060Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_5060_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service5222Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_5222_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service5432Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_5432_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service5800Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_5800_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service5900Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_5900_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service623Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_623_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service632Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_632_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service8080Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_8080_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service80Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_80_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service902Tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'service_902_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SmbDetailsTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(db_column='OS', max_length=100)),
                ('host', models.CharField(blank=True, max_length=100, null=True)),
                ('hostname', models.CharField(blank=True, max_length=100, null=True)),
                ('signing', models.CharField(blank=True, max_length=100, null=True)),
                ('timpestamp', models.DateField(blank=True, null=True)),
                ('compromised', models.CharField(blank=True, max_length=100, null=True)),
                ('subnet', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'smb_details_tbl',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubnetsTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.IntegerField()),
                ('subnet', models.CharField(db_column='Subnet', max_length=100)),
                ('subnet_id', models.IntegerField(db_column='Subnet_id')),
                ('timpestamp', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subnets_tbl',
                'managed': True,
            },
        ),
    ]
