# Generated by Django 3.2.7 on 2022-01-21 07:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredUsers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_firstname', models.CharField(max_length=400)),
                ('user_lastname', models.CharField(max_length=400)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250)),
            ],
        ),
        migrations.AlterModelOptions(
            name='domainusershashtbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='domainuserspasswordtbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='finalhoststbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='findingstbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='issue1tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='issue2tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='issue3tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='issue4tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='issue5tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='issue6tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='issue7tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mssqltbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pathstbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='progresstbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='revalidationtbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='scanidtbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service135tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service137tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service1433tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service1521tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service17988tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service2049tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service21tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service22tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service23tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service25tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service27017tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service3250tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service3260tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service3306tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service3389tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service389tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service443tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service445tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service5060tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service5222tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service5432tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service5800tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service5900tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service623tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service632tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service8080tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service80tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='service902tbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='smbdetailstbl',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='subnetstbl',
            options={'managed': False},
        ),
    ]
